export const vehidlesDataMock = {
  code: 200,
  message: "Ok",
  value: {
    vehicles: [
      {
        id: 0,
        carNumber: "TX-001",
        carLabel: "Toyota Hilux",
        carShortcut: "HILUX",
      },
      {
        id: 1,
        carNumber: "TX-002",
        carLabel: "Ford Ranger",
        carShortcut: "RANGER",
      },
      {
        id: 2,
        carNumber: "TX-003",
        carLabel: "Chevrolet S10",
        carShortcut: "S10",
      },
      {
        id: 3,
        carNumber: "TX-004",
        carLabel: "Nissan Frontier",
        carShortcut: "FRONT",
      },
      {
        id: 4,
        carNumber: "TX-005",
        carLabel: "Volkswagen Amarok",
        carShortcut: "AMAROK",
      },
      {
        id: 5,
        carNumber: "TX-006",
        carLabel: "Mitsubishi L200",
        carShortcut: "L200",
      },
      {
        id: 6,
        carNumber: "TX-007",
        carLabel: "Isuzu D-Max",
        carShortcut: "DMAX",
      },
      {
        id: 7,
        carNumber: "TX-008",
        carLabel: "Ram 700",
        carShortcut: "RAM700",
      },
      {
        id: 8,
        carNumber: "TX-009",
        carLabel: "Hyundai Santa Fe",
        carShortcut: "SFE",
      },
      {
        id: 9,
        carNumber: "TX-010",
        carLabel: "Kia Sportage",
        carShortcut: "SPORT",
      },
      {
        id: 10,
        carNumber: "TX-011",
        carLabel: "Jeep Gladiator",
        carShortcut: "GLAD",
      },
      {
        id: 11,
        carNumber: "TX-012",
        carLabel: "Mazda BT-50",
        carShortcut: "BT50",
      },
      {
        id: 12,
        carNumber: "TX-013",
        carLabel: "Renault Oroch",
        carShortcut: "OROCH",
      },
      {
        id: 13,
        carNumber: "TX-014",
        carLabel: "Fiat Toro",
        carShortcut: "TORO",
      },
      {
        id: 14,
        carNumber: "TX-015",
        carLabel: "Peugeot Landtrek",
        carShortcut: "LAND",
      },
      {
        id: 15,
        carNumber: "TX-016",
        carLabel: "Honda Ridgeline",
        carShortcut: "RIDGE",
      },
      {
        id: 16,
        carNumber: "TX-017",
        carLabel: "Subaru Baja",
        carShortcut: "BAJA",
      },
      {
        id: 17,
        carNumber: "TX-018",
        carLabel: "Suzuki Carry",
        carShortcut: "CARRY",
      },
      {
        id: 18,
        carNumber: "TX-019",
        carLabel: "Mercedes X-Class",
        carShortcut: "XCLASS",
      },
      {
        id: 19,
        carNumber: "TX-020",
        carLabel: "Great Wall Wingle",
        carShortcut: "WINGLE",
      },
    ],
  },
};
