import { Drivers } from "../redux/serviceSlices/driversSlice";

export const driversDataMock: Drivers[] = [
  {
    id: 1,
    name: "Carlos",
    email: "carlos.mendez@example.com",
    lastName: "Méndez",
    address: "Av. Revolución 123, Guadalajara, Jalisco",
    entryDate: "2024-01-15",
    alias: "Carlitos",
    groupName: "Logística Norte",
    license: "LIC-JAL-458721",
  },
  {
    id: 2,
    name: "Andrea",
    email: "andrea.ruiz@example.com",
    lastName: "Ruiz",
    address: "Calle Hidalgo 456, Monterrey, Nuevo León",
    entryDate: "2023-09-08",
    alias: "Andy",
    groupName: "Distribución Urbana",
    license: "LIC-NL-874512",
  },
  {
    id: 3,
    name: "Luis",
    email: "luis.herrera@example.com",
    lastName: "Herrera",
    address: "Blvd. Independencia 789, León, Guanajuato",
    entryDate: "2022-06-21",
    alias: "Lucho",
    groupName: "Operación Bajío",
    license: "LIC-GTO-214563",
  },
  {
    id: 4,
    name: "Mariana",
    email: "mariana.soto@example.com",
    lastName: "Soto",
    address: "Calle Morelos 321, Puebla, Puebla",
    entryDate: "2025-02-11",
    alias: "Mare",
    groupName: "Operación Sur",
    license: "LIC-PUE-963258",
  },
  {
    id: 5,
    name: "José",
    email: "jose.ramirez@example.com",
    lastName: "Ramírez",
    address: "Av. Patria 654, Zapopan, Jalisco",
    entryDate: "2021-11-30",
    alias: "Pepe",
    groupName: "Carga Pesada",
    license: "LIC-JAL-741852",
  },
];
