import { Vehicles } from "../redux/serviceSlices/vehiclesSlice";

export const vehiclesDataMock: Vehicles[] = [
  {
    id: 1,
    plate: "JAL-482-A",
    name: "Unidad Norte 01",
    brand: "Kenworth",
    model: "T680",
    vehicleType: "Tractocamión",
    year: "2022",
    serialNumber: "3KWTB49X7NF234561",
    driver: "Luis Herrera",
    group: [
      { id: "1", name: "Logística Norte" },
      { id: "2", name: "Carga Pesada" },
    ],
    imeIs: ["356789012345678", "356789012345679"],
  },
  {
    id: 2,
    plate: "CDMX-913-Z",
    name: "Reparto Centro 12",
    brand: "Nissan",
    model: "NP300",
    vehicleType: "Pickup",
    year: "2021",
    serialNumber: "1N6AD0EV4MN745210",
    driver: "Mariana Soto",
    group: [{ id: "3", name: "Distribución Urbana" }],
    imeIs: ["867451230987654"],
  },
  {
    id: 3,
    plate: "GDL-220-K",
    name: "Transporte Ejecutivo 03",
    brand: "Toyota",
    model: "Hiace",
    vehicleType: "Van",
    year: "2020",
    serialNumber: "JTFSX23P4L5001842",
    driver: "Carlos Méndez",
    group: [{ id: "4", name: "Transporte Personal" }],
    imeIs: [],
  },
  {
    id: 4,
    plate: "MTY-771-P",
    name: "Carga Ligera 07",
    brand: "Ford",
    model: "Transit",
    vehicleType: "Van de carga",
    year: "2023",
    serialNumber: "WF0XXXTTGXPK88214",
    driver: "Andrea Ruiz",
    group: [
      { id: "2", name: "Carga Pesada" },
      { id: "5", name: "Operación Monterrey" },
    ],
    imeIs: ["352099001234567"],
  },
  {
    id: 5,
    plate: "PUE-558-M",
    name: "Unidad Sur 05",
    brand: "Freightliner",
    model: "M2 106",
    vehicleType: "Camión",
    year: "2019",
    serialNumber: "3ALACXFC5KDK12890",
    driver: "José Ramírez",
    group: [{ id: "6", name: "Operación Sur" }],
    imeIs: [],
  },
];
