import {
  ZoneProfileDetailsExtends,
  ZoneProfileDetailsValue,
} from "../redux/serviceSlices/zoneProfileDetailsSlice";

const zoneProfiles: ZoneProfileDetailsExtends[] = [
  {
    accountId: "5001",
    chargeState: 1,
    color: "#4CAF50",
    description: "Estación de carga principal",
    dischargeState: 0,
    idProfile: "zp_001",
    idleState: 0,
    nick: "Carga Centro",
    zoneCategoryId: "zc_01",
    zoneCategoryName: "Estaciones de servicio",
    zoneId: "zone_001",
    zoneName: "Gasolinera Centro",
    zoneProviderId: "prov_01",
    zoneProviderName: "Proveedor Interno",
  },
  {
    accountId: "5001",
    chargeState: 0,
    color: "#FF9800",
    description: "Zona de espera de vehículos",
    dischargeState: 0,
    idProfile: "zp_002",
    idleState: 1,
    nick: "Patio Norte",
    zoneCategoryId: "zc_02",
    zoneCategoryName: "Patios",
    zoneId: "zone_002",
    zoneName: "Patio Logístico Norte",
    zoneProviderId: "prov_01",
    zoneProviderName: "Proveedor Interno",
  },
  {
    accountId: "5001",
    chargeState: 0,
    color: "#F44336",
    description: "Zona con historial de descargas de combustible",
    dischargeState: 1,
    idProfile: "zp_003",
    idleState: 0,
    nick: "Zona Riesgo",
    zoneCategoryId: "zc_03",
    zoneCategoryName: "Zonas monitoreadas",
    zoneId: "zone_003",
    zoneName: "Área Industrial Sur",
    zoneProviderId: "prov_02",
    zoneProviderName: "Proveedor Externo",
  },
  {
    accountId: "5001",
    chargeState: 0,
    color: "#2196F3",
    description: "Centro de distribución principal",
    dischargeState: 0,
    idProfile: "zp_004",
    idleState: 0,
    nick: "CEDIS",
    zoneCategoryId: "zc_04",
    zoneCategoryName: "Centros logísticos",
    zoneId: "zone_004",
    zoneName: "Centro de Distribución Veracruz",
    zoneProviderId: "prov_01",
    zoneProviderName: "Proveedor Interno",
  },
  {
    accountId: "5001",
    chargeState: 0,
    color: "#9C27B0",
    description: "Zona de descanso de operadores",
    dischargeState: 0,
    idProfile: "zp_005",
    idleState: 1,
    nick: "Descanso Sur",
    zoneCategoryId: "zc_05",
    zoneCategoryName: "Áreas de descanso",
    zoneId: "zone_005",
    zoneName: "Parador Sur",
    zoneProviderId: "prov_02",
    zoneProviderName: "Proveedor Externo",
  },
];

export const zoneProfileDetailsDataDataMock: ZoneProfileDetailsValue = {
  zoneProfileDetailsExtends: zoneProfiles,
};
