import { Zone } from "../redux/serviceSlices/zonesSummary";

export const zonesDataMock: Zone[] = [
  {
    zoneName: "Patio Central Guadalajara",
    zoneId: "ZAP-001",
    profileName: "Operación Occidente",
    country: "México",
    state: "Jalisco",
    city: "Guadalajara",
    postalCode: "44100",
    totalEvents: 18,
    loadedLiters: 1240.5,
    unloadedLiters: 185.3,
  },
  {
    zoneName: "Terminal Norte Monterrey",
    zoneId: "MTY-003",
    profileName: "Operación Norte",
    country: "México",
    state: "Nuevo León",
    city: "Monterrey",
    postalCode: "64000",
    totalEvents: 11,
    loadedLiters: 842.7,
    unloadedLiters: 96.4,
  },
  {
    zoneName: "Centro Logístico Puebla",
    zoneId: "PUE-019",
    profileName: "Operación Centro",
    country: "México",
    state: "Puebla",
    city: "Puebla",
    postalCode: "72000",
    totalEvents: 9,
    loadedLiters: 690.2,
    unloadedLiters: 74.8,
  },
  {
    zoneName: "Base Industrial León",
    zoneId: "LEON-008",
    profileName: "Operación Bajío",
    country: "México",
    state: "Guanajuato",
    city: "León",
    postalCode: "37260",
    totalEvents: 14,
    loadedLiters: 975.9,
    unloadedLiters: 121.6,
  },
  {
    zoneName: "Planta Sur Tlaquepaque",
    zoneId: "TLA-009",
    profileName: "Operación Metropolitana",
    country: "México",
    state: "Jalisco",
    city: "Tlaquepaque",
    postalCode: "45601",
    totalEvents: 7,
    loadedLiters: 514.3,
    unloadedLiters: 58.1,
  },
];
