export const usersDataMock = {
  code: 200,
  message: "Ok",
  value: {
    users: [
      {
        id: 3238,
        userName: "Benjamín",
        name: "Benjamín",
        lastName: "Sanchez",
        email: "benjamin.sanchez@innovaria.com.mx",
      },
      {
        id: 3376,
        userName: "Daniel",
        name: "Daniel",
        lastName: "García",
        email: "daniel.garcia@innovaria.com.mx",
      },
      {
        id: 3385,
        userName: "Jorge",
        name: "Jorge",
        lastName: "Meza",
        email: "jorge.meza@innovaria.com.mx",
      },
      {
        id: 3903,
        userName: "Jonathan",
        name: "Jonathan",
        lastName: "Diaz",
        email: "jonathan.diaz@innovaria.com.mx",
      },
      {
        id: 3992,
        userName: "Alfredo",
        name: "Alfredo",
        lastName: "Warelan",
        email: "alfredo@warelan.com",
      },
      {
        id: 4024,
        userName: "Jonathan",
        name: "Jonathan",
        lastName: "Morales",
        email: "jonathan.morales@transtelemetrix.com",
      },
      {
        id: 4025,
        userName: "Edgar",
        name: "Edgar",
        lastName: "Chavez",
        email: "edgar.chavez@transtelemetrix.com",
      },
      {
        id: 4026,
        userName: "Jonathan",
        name: "Jonathan",
        lastName: "Diaz",
        email: "jonathan.diaz@transtelemetrix.com",
      },
      {
        id: 4027,
        userName: "Sergio",
        name: "Sergio",
        lastName: "Gonzalez",
        email: "sergio.gonzalez@transtelemetrix.com",
      },
      {
        id: 4176,
        userName: "Ricardo",
        name: "Ricardo",
        lastName: "Saldivar",
        email: "ricardo.saldivar@innovaria.com.mx",
      },
      {
        id: 4316,
        userName: "Juan",
        name: "Juan",
        lastName: "Rodriguez",
        email: "juanrodriguez@email.com",
      },
      {
        id: 4317,
        userName: "Luis",
        name: "Luis",
        lastName: "De la Hialga",
        email: "luis@email.com",
      },
      {
        id: 4350,
        userName: "Ivan",
        name: "Ivan",
        lastName: "Rosales",
        email: "ivan.rosales@transtelemetrix.com",
      },
      {
        id: 4363,
        userName: "Carlos",
        name: "Carlos",
        lastName: "Tena",
        email: "carlostenahernandez@gmail.com",
      },
      {
        id: 4400,
        userName: "Jhon",
        name: "Jhon",
        lastName: "Peña",
        email: "jhon.pena@innovaria.com.mx",
      },
      {
        id: 4430,
        userName: "Transtelemetrix",
        name: "Transtelemetrix",
        lastName: "SW Dev",
        email: "sw.dev@transtelemetrix.com",
      },
    ],
  },
};
